import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'A and Z',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='flex h-screen'>
          <div className='hidden md:block h-screen w-1/2 bg-[#D9DEEF] '>
            <Image 
              src="/assets/images/Rectangle 21.png"
              alt="logo"
              width={600}
              height={500}
              className="h-screen"
            />
          </div>
          <section className='flex relative bg-[#D9DEEF] flex-1 justify-center items-center flex-col '>
            {children}
          </section>
        </main>
      </body>
    </html>
  )
}
